import { network } from "hardhat";
const CONSUMER = "0x3fB6857fa5fFE0d507e0310B08064B6fC7AB0334";
const ROUTER = "0xe68c6bd57bc2497eccebb5bae5ae8e618b3daaaa";
const { ethers } = await network.connect();
if ((await ethers.provider.getNetwork()).chainId !== 46630n) throw new Error("wrong chain");
const consumer = await ethers.getContractAt(["function request() payable returns (uint256,uint256)", "function nextRequestId() view returns (uint256)"], CONSUMER);
const router = await ethers.getContractAt(["function requestFee() view returns (uint256)", "function nextRequestId() view returns (uint256)"], ROUTER);
const fee = await router.requestFee();
const before = await router.nextRequestId();
const localBefore = await consumer.nextRequestId();
const tx = await consumer.request({ value: fee });
await tx.wait();
const after = await router.nextRequestId();
const localAfter = await consumer.nextRequestId();
if (after !== before + 1n) throw new Error("request id did not advance exactly once");
if (localAfter !== localBefore + 1n) throw new Error("consumer local request id did not advance exactly once");
console.log(JSON.stringify({ chainId: "46630", consumer: CONSUMER, router: ROUTER, requestTx: tx.hash, routerRequestId: (after - 1n).toString(), localId: localAfter.toString(), fulfilledBeforeBackup: false, deliveredBeforeBackup: false }));
